# XGBoost for Whale Classification

In this assignment, you have been provided a dataset that consists of echo-location clicks of two types of whales, namely, Gervais and Cuviers. Your task is to classify the different types whales using Gradient Boosting with the help of the XGBoost library. You are expected to fill in functions that would complete this task. We use XGBoost here instead of GradientBoostedTrees in Spark because XGBoost running on a single machine is much faster than Spark running on 10 machines.

The data files were preprocessed on PySpark (10 nodes) cluster. The code for the same can be found in Data_Processing_Whales.ipynb. The preprocessed data is a numpy array with `4175` rows (for the 10mb file) with following columns (zero-indexed):
* Col 0-9: projections on first 10 eigen vectors
* Col 10: rmse
* Col 11: peak2peak
* Col 12: label (`0 if row.species==u'Gervais' else 1`)

You can also refer to XGBoost_Whales.ipynb under for more details on the XGBoost Analysis before you attempt this assignment.

Both Data_Processing_Whales.ipynb and XGBoost_Whales.ipynb can be found under XGBoost directory that was uploaded in edX as a part of "Notebooks for weeks 7 & 8". 

## XGBoost - Theory

A brief overview of gradient boosting in XGBoost can be found here:

* https://xgboost.readthedocs.io/en/latest/tutorials/model.html
* https://xgboost.readthedocs.io/en/latest/python/python_intro.html

Use the XGBoost API for training and predicting scores: 

* http://xgboost.readthedocs.io/en/latest/python/python_api.html

#### Main API

* `xgboost.train` is the learning API that trains the Gradient Boosting Model,
   * The main parameters are:
      * **plst** – XGBoost parameter list
      * **dtrain** – Data to be trained
      * **num_round** – Number of iterations of boosting. (default: 100)
      * **evallist** – List of items to be evaluated during training
      * **verbose_eval** - This can be used to control how much information the train function prints. You might want to set to **False** to avoid printing logs.
* `bst.predict` is the API that makes score predictions
   * The main parameters are:
      * **dtest** – Test Data
      * **dtrain** – Data to be trained
      * **ntree_limit** – Limit number of trees in the prediction (Use: ntree_limit=bst.best_ntree_limit)
      * **output_margin** - Whether to output the raw untransformed margin value (Use: output_margin=True)

## Notebook Setup

### Importing Required Libraries

In [1]:
%load_ext autoreload
!pip3 install xgboost

Defaulting to user installation because normal site-packages is not writeable


In [2]:
%matplotlib inline
import numpy as np
import xgboost as xgb
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import pickle
import random

In [3]:
xgb.__version__

'1.7.5'

### Loading Data

In [4]:
import os
path = os.getcwd()
_uname = path.split('/')[2]
print("Username =", _uname)

Username = jiy068


In [5]:
with open(f'/home/{_uname}/public/Datasets_public/hw4_publicdata/X_train.pkl', 'rb') as f:
    X_train = pickle.load(f)

with open(f'/home/{_uname}/public/Datasets_public/hw4_publicdata/X_test.pkl', 'rb') as f:
    X_test = pickle.load(f)

with open(f'/home/{_uname}/public/Datasets_public/hw4_publicdata/y_train.pkl', 'rb') as f:
    y_train = pickle.load(f)

with open(f'/home/{_uname}/public/Datasets_public/hw4_publicdata/y_test.pkl', 'rb') as f:
    y_test = pickle.load(f)

### Setting Parameters for XG Boost
* Maximum Depth of the Tree = 3 _(maximum depth of each decision trees)_
* Step size shrinkage used in update to prevents overfitting = 0.3 _(how to weigh trees in subsequent iterations)_
* Evaluation Criterion= Maximize Loglikelihood according to the logistic regression _(logitboost)_
* Maximum Number of Iterations = 1000 _(total number trees for boosting)_
* Early Stop if score on Validation does not improve for 5 iterations

[Full description of options](https://xgboost.readthedocs.io/en/latest/parameter.html)

In [6]:
#You can change this cell if you wish to, but you aren't expected to
def xgboost_plst():
    param = {}
    param['max_depth']= 3   # depth of tree
    param['eta'] = 0.3      # shrinkage parameter
    param['objective'] = 'binary:logistic'
    param['nthread'] = 7 # Number of threads used
    param['eval_metric'] = 'logloss'
    return param

## Exercises

### Computing the score ranges

The function `calc_stats` takes the xgboost margin scores as input and returns two numpy arrays `min_scr`, `max_scr` which are calculated as follows:

1. `min_scr`: mean - (3 $\times$ std)
2. `max_scr`: mean + (3 $\times$ std)

Here the input margin scores, represents the processed XGBoost margin scores obtained from the `bootstrap_pred` function. Each row represents the various scores for a specific example in an iteration and your `calc_stats` function is supposed to compute the `min_scr` and `max_scr` as defined for each example. So in the example below, we take a scenario where we have 3 examples which have 4 values each (From 4 bootstrap iterations).

#### Tasks:

Finish the function `calc_stats`.

Input:

- `margin_scores`: a 2d numpy array that contains xgboost margin scores. 

Output: 

- 2 numpy arrays of `min_scr` and `max_scr` as defined above. 


**Note**: Ensure you round the values in the numpy arrays to two decimal places

---

**<font color="magenta" size=2>Example Input</font>**
``` python
[[-0.22 -0.19 -0.17 -0.13][-0.1 -0.05 0.02 0.10][0.03 0.11 0.12 0.15]]
```


**<font color="blue" size=2>Example Output</font>**
``` python
(array([-0.28 -0.23 -0.03]),
 array([-0.08  0.22  0.24]))
```

In [7]:
def calc_stats(margin_scores):
    # YOUR CODE HERE
    mean = np.mean(margin_scores, axis = 1)
    std = np.std(margin_scores, axis = 1)
    min_scr = np.around(mean - 3 * std, decimals=2)
    max_scr = np.around(mean + 3 * std, decimals=2)
    return min_scr, max_scr

In [8]:
margin_score = np.array([[-0.22, -0.19, -0.17, -0.13], [-0.1, -0.05, 0.02, 0.10], [0.03, 0.11, 0.12, 0.15]])
min_score, max_score = calc_stats(margin_score)
assert type(min_score) == np.ndarray, 'Incorrect Return type'
assert type(max_score) == np.ndarray, 'Incorrect Return type'

In [9]:
assert (min_score == np.array([-0.28, -0.23, -0.03])).all(), "Incorrect return value"

In [10]:
assert (max_score == np.array([-0.08,  0.22,  0.24])).all(), "Incorrect return value"

In [11]:
# Hidden Tests Here

In [12]:
# Hidden Tests Here

### Calculating predictions

Based on the ranges for each of the examples, i.e, (`min_scr`, `max_scr`), we can predict whether it's a Gervais or a Cuvier. Since all our scores will be between -1 and +1, we use 0 as the margin line. All examples which are on the left side of the margin, can be classified as Cuvier's and all which are on the right side can be classified as Gervais. However, since we take margin scores from a set of bootstraps for each example, we use the minimum and maximum score arrays to predict to determine the classification.

#### Tasks:

Finish the function `predict`, which takes the minimum score array and maximum score array and returns predictions as follows:

1. If respective minimum score and maximum score values are less than 0, predict -1 (**Cuvier's**)
2. If respective minimum score value is less than 0 and maximum score value is greater than 0, predict 0 (**Unsure**)
3. If respective minimum score and maximum score values are greater than 0, predict 1 (**Gervais**)


Input:

- `min_scr`: the numpy array from `calc_stats`

- `max_scr`: the numpy array from `calc_stats`

Output: 

- a numpy array of predictions

---

**<font color="magenta" size=2>Example Input</font>**
``` python
min_scr (numpy array) = [-0.78 -0.68 -0.6 -0.53 -0.47 -0.42 -0.32 -0.21 -0.07 0.22]

max_scr (numpy array) = [-0.49 -0.39 -0.33 -0.25 -0.2 -0.11 -0.04 0.1 0.3 0.51]
```

**<font color="blue" size=2>Example Output</font>**
``` python
[-1 -1 -1 -1 -1 -1 -1  0  0  1]
```

In [13]:
def predict(min_scr, max_scr):
    # YOUR CODE HERE
    n = len(min_scr)
    pred = np.zeros(n)
    for i in range(n):
        if max_scr[i] < 0:
            pred[i] = -1
        elif min_scr[i] > 0:
            pred[i] = 1
    return pred

In [14]:
max_s = np.array([-0.49, -0.39, -0.33, -0.25, -0.2, -0.11, -0.04, 0.1, 0.3, 0.51])
min_s = np.array([-0.78, -0.68, -0.6, -0.53, -0.47, -0.42, -0.32, -0.21, -0.07, 0.22])
pred = predict(min_s, max_s)
true_pred = np.array([-1, -1, -1, -1, -1, -1, -1, 0, 0, 1])

In [15]:
assert type(pred) == np.ndarray, 'Incorrect return type'

In [16]:
assert (pred == true_pred).all(), 'Incorrect return value'

### Calculating scores

You can follow these procedures to train a number of XGBoost models using bootstrap and test their performances.

Repeat the given procedure for `n_bootstrap` number of iterations:

For `n_bootstrap` iterations:
* Sample `boostrap_size` indices from the training set **with replacmennt**.
* Create train and test data matrices `(dtrain, dtest)` using `xgb.DMatrix(X_sample, label=y_sample)`.
* Initialise the `evallist` parameter `[(dtrain, 'train'), (dtest, 'eval')]`.
* Train the model using the XGBoost train API and make score predictions using bst.predict object returned by XGB train API. **Ensure you set `output_margin=True` to get raw untransformed output scores and `ntree_limit=bst.best_ntree_limit`**.
* Normalize them by dividing them with the normalizing factor as `max(scores) - min(scores)` and round these values to a precision of two decimal places.

Then: 
* For each individual example, remove scores below the minRth score and greater than the maxRth score(sort for each example if necessary).
* Call the `calc_stats` function to compute `min_scr` and `max_scr` with the filtered margin scores as parameter.
* Return the `min_scr` and `max_scr` computed by the `calc_stat` function using the margin scores.

#### Task:

Finish the function `bootstrap_pred`.

Input:

- `Training set`: the training set.
- `Test set`: the test test.
- `n_bootstrap`: number of bootstrap samples that run XGBoost and trains one part of the sample set.
- `minR, maxR`: two numbers such that $0 < minR < maxR < 1$ that define the fractions of the `n_bootstrap` scores that define the range.
- `bootstrap_size`: number of bootstrap samples on which you will run XGBoost.
- `num_round`: number of iterations for running xgboost.
- `plst`: parameter List.

Output:

- The output should be a confidence interval for each example in the test set (`min_scr` and `max_scr`). 

**Note**: 

- Please see the [Main API](#Main-API) section above to see how to use XGBoost.
- Remember to set `num_round` and `plst` as specified by the parameters in `xgb.train`.
- You can experiment by changing `n_bootstraps`, but it takes about 200 iterations to get consistent values.

In [17]:
def bootstrap_pred(X_train, X_test, y_train, y_test, n_bootstrap, minR, maxR, bootstrap_size, \
                   num_round=100, plst=xgboost_plst()):
    # YOUR CODE HERE
    margin_score = None
    for i in range(n_bootstrap):
        indices = np.random.choice(X_train.shape[0], bootstrap_size)
        X_sample = X_train[indices]
        y_sample = y_train[indices]
        dtrain = xgb.DMatrix(X_sample, label=y_sample)
        dtest = xgb.DMatrix(X_test, label=y_test)
        
        bst = xgb.train(params=plst, dtrain=dtrain, num_boost_round=num_round, 
                    verbose_eval=False, evals=[(dtrain, 'train'), (dtest, 'eval')])
        scores = bst.predict(dtest, output_margin=True, iteration_range=(0, bst.best_iteration + 1))
        scores = np.around(scores / (max(scores) - min(scores)), decimals=2)
        scores = scores.reshape((len(scores), 1))
        margin_score = np.hstack((margin_score, scores)) if margin_score is not None else scores
        
    margin_score = np.sort(margin_score, axis=1)
    left = int(n_bootstrap*minR)
    right = int(n_bootstrap*maxR)
    margin_score = margin_score[:, left:right]
    return calc_stats(margin_score)

In [18]:
def process(X_train, X_test, y_train, y_test, n_bootstrap=100):
    min_scr, max_scr = bootstrap_pred(X_train, X_test, y_train, y_test, n_bootstrap=n_bootstrap, \
                                            minR=0.1, maxR=0.9, bootstrap_size=len(X_train))
    pred = predict(min_scr, max_scr)
    return min_scr, max_scr, pred

#### Tests

How we test the function:
1. We have computed the average mid-point of the range of values and verify that this midpoint is present in the range computed by your function
2. We check that the length of the `interval(max_scr-min_scr)` is not more than twice the average length of the interval

In [36]:
sample_indices = np.load(f'/home/{_uname}/public/Datasets_public/hw4_publicdata/vis_indices.npy')
X_test_samp = X_test[sample_indices]
y_test_samp = np.array(y_test[sample_indices], dtype=int)
midpt = np.load(f'/home/{_uname}/public/Datasets_public/hw4_publicdata/vis_midpt.npy')
avg_length = np.load(f'/home/{_uname}/public/Datasets_public/hw4_publicdata/vis_avg_length.npy')
min_scr, max_scr, pred = process(X_train, X_test_samp, y_train, y_test_samp)
length = max_scr - min_scr

In [37]:
assert sum(min_scr <= midpt) >= (0.7 * len(sample_indices)), "Incorrect range (mean - 3*std) to (mean + 3*std)"

In [38]:
assert sum(max_scr >= midpt) >= (0.7 * len(sample_indices)), "Incorrect range (mean - 3*std) to (mean + 3*std)"

In [39]:
assert sum(length < 2*avg_length) >= (0.7 * len(sample_indices)), "Incorrect length of range (mean - 3*std) to (mean + 3*std)"

In [40]:
# Hidden Tests Here

In [24]:
# Hidden Tests Here

In [25]:
# Hidden Tests Here

In [26]:
# Hidden Tests Here

In [27]:
# Hidden Tests here

In [28]:
# Hidden Tests here

In [29]:
# Hidden Tests here

In [30]:
# Hidden Tests here